apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: flinksqljobs.dev.henneberger
spec:
  group: dev.henneberger
  names:
    kind: FlinkSqlJob
    plural: flinksqljobs
    singular: flinksqljob
    shortNames:
      - fsql
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - image
                - sql
              properties:
                image:
                  type: string
                sql:
                  type: string
                parallelism:
                  type: integer
                  minimum: 1
                flinkVersion:
                  type: string
                  default: v1_19
                jobName:
                  type: string
                serviceAccount:
                  type: string
                pythonRefs:
                  type: array
                  items:
                    type: string
                catalogRefs:
                  type: array
                  items:
                    type: string
                schedule:
                  type: object
                  properties:
                    maxRunTime:
                      type: string
                    rekickInterval:
                      type: string
                    priority:
                      type: integer
                overrides:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  properties:
                    merge:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    patches:
                      type: array
                      items:
                        type: object
                        required:
                          - op
                          - path
                        properties:
                          op:
                            type: string
                          path:
                            type: string
                          value:
                            x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                state:
                  type: string
                message:
                  type: string
                flinkDeploymentName:
                  type: string
                activeStartTime:
                  type: string
                lastKickTime:
                  type: string
                lastStopTime:
                  type: string
      subresources:
        status: {}
