apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kafkaconnections.vertx.henneberger.dev
spec:
  group: vertx.henneberger.dev
  names:
    kind: KafkaConnection
    plural: kafkaconnections
    singular: kafkaconnection
    shortNames:
      - vxkc
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - bootstrapServers
              properties:
                bootstrapServers:
                  type: string
                clientId:
                  type: string
                acks:
                  type: string
                  default: all
                lingerMs:
                  type: integer
                  default: 5
                batchSize:
                  type: integer
                  default: 16384
                replicas:
                  type: integer
                  default: 1
                servicePort:
                  type: integer
                  default: 8080
                image:
                  type: string
